import type { Metadata } from "next";
import "./globals.css";
import { baseFont } from "@/config/fonts";
import { SideBar, TopMenu } from "@/components";
import { GptHead } from "@/components/ad/gpt";

export const metadata: Metadata = {
  title: "Diario La R",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={baseFont.className}>
        <GptHead />

        <TopMenu />
        <SideBar />

        <main className="min-h-screen container mx-auto px-5 lg:w-[1280px] shadow bg-gray-100">
          {children}
        </main>
      </body>
    </html>
  );
}
